### ISSUE TITLE
1.46.11 is returning a HTTP Status 404 

### ISSUE THREAD

**Issue by delijati** [maugenst/openui5.runtime.downloader#1]
The current version `1.46.11` is not working anymore `https://openui5.hana.ondemand.com/downloads/openui5-runtime-1.46.11.zip` returns a `404`. The version `https://openui5.hana.ondemand.com/downloads/openui5-runtime-1.46.12.zip` is working.

**Comment by maugenst** [comment]
ok ... missed the latest release... going to fix it asap.

**Comment by maugenst** [comment]
version increased to 1.46.12...
